Adds lagoon_logs, adds some minimal checking to semilock build script

diff --git a/build/build_semilock b/build/build_semilock
--- a/build/build_semilock
+++ b/build/build_semilock
@@ -2,8 +2,13 @@
 cd /app
 pwd
 echo "{}" > composer.lock #we don't delete it because it's mapped
-COMPOSER=composer.true.json composer install
-cd /app/build
-pwd
-composer install
-./vendor/bin/semilock composer_fixed:generate /app/composer.true.json /app/composer.true.lock > ../composer.json && rm ../composer.true.lock
+COMPOSER=composer.true.json composer install 
+if [[ $? -eq 0 ]]; then
+	cd /app/build
+	pwd
+      	composer install
+      	./vendor/bin/semilock composer_fixed:generate /app/composer.true.json /app/composer.true.lock > ../composer.json && rm ../composer.true.lock
+  else
+	echo "Unable to install composer.true.json - exiting"
+	exit 1
+fi
